version: '3.9'
services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:4.0-alpine

  web:
    build: .
    command: >
      sh -c "
        rm -rf tmp/pids/server.pid \
        & ./bin/webpack-dev-server \
        & bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/google-search-from-csv
      - /var/www/google-search-from-csv/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    tty: true
    stdin_open: true

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    working_dir: /var/www/google-search-from-csv
    volumes:
      - .:/var/www/google-search-from-csv

volumes:
  postgres-data:
